events {}

http {

    server {

        listen 80;

        location / {

            return 200 "E-Commerce Site Running\n";

        }

        location /login {

            proxy_pass http://auth:5000/login;

        }

        location /health/auth {

            proxy_pass http://auth:5000/health;

        }

        location /orders {

            proxy_pass http://order:5001/orders;

        }
    }
}