events {}

http {

    server {

        listen 80;

        location / {

            return 200 "E-Commerce Platform Online\n";

        }

        location /login {

            proxy_pass http://10.20.20.30:5000/login;

        }

        location /orders {

            proxy_pass http://10.20.20.40:5001/orders;

        }

        location /health/auth {

            proxy_pass http://10.20.20.30:5000/health;

        }

        location /health/order {

            proxy_pass http://10.20.20.40:5001/health;

        }
    }
}